version: '3'
services:
  migrate:
    image: topix_app 
    command: node_modules/.bin/sequelize db:migrate
    depends_on:
      - app
    environment:
      DATABASE_URI: ${DATABASE_URI}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      API_PORT: ${API_PORT}
  app:
    build: .
    command: start
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
    environment:
      DATABASE_URI: ${DATABASE_URI}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      API_PORT: ${API_PORT}
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
