version: '3'
services:
  topix_user_api:
    build: .
    command: start
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - topix_db
    environment:
      MONGO_HOST: topix_db
      MONGO_USER: ${MONGO_USER}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      API_PORT: ${API_PORT}
  topix_db:
    image: mongo:4-xenial
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
