version: '3'
services:
  user_api:
    build: .
    command: start
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      MONGO_HOST: db
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PORT: 27017
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
  db:
    image: vepo/mongo
    ports:
      - "27017:27017"
    environment:
      AUTH: "yes"
      ADMIN_USER: ${MONGO_USERNAME}
      ADMIN_PASS: ${MONGO_PASSWORD}
      APPLICATION_DATABASE: ${MONGO_DATABASE}
      APPLICATION_USER: ${MONGO_USERNAME}
      APPLICATION_PASS: ${MONGO_PASSWORD}
