version: '3'
services:
  api:
    build: .
    command: sh -c "/wait && npm start"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      MONGO_HOST: db
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PORT: 27017
      JWT_SECRET: ${JWT_SECRET}
      WAIT_HOSTS: db:27017
  redis:
    image: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - topix-redis-data:/data
  db:
    image: vepo/mongo
    ports:
      - 27017:27017
    environment:
      AUTH: "yes"
      ADMIN_USER: ${MONGO_USERNAME}
      ADMIN_PASS: ${MONGO_PASSWORD}
      APPLICATION_DATABASE: ${MONGO_DATABASE}
      APPLICATION_USER: ${MONGO_USERNAME}
      APPLICATION_PASS: ${MONGO_PASSWORD}
volumes:
  topix-redis-data: